global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus' #job of himself
    static_configs:
      - targets: ['localhost:9090'] 
  - job_name: 'node' #to scrape metrics of the current machine
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'alertmanager' # job for Alertmanager
    static_configs:
      - targets: ['localhost:9093']
# for scrape from a remote machine
  - job_name: 'node_exporter_macchina' 
    static_configs:
      - targets: ['xxx.xxx.xxx.xxx:9100']

# link to alertmanager installed on port 9093
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

# The alert .yml files are all located in a subdirectory called alert_rule
rule_files: 
  - "alert_rule/test_alert_rule.yml" 
  - "alert_rule/alert_disk_usage.yml"
