{
 "title": "Cpu for all machine",
 "tags": [ "Cpu" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Tempo di attesa e stallo I/O del Sistema",
   "type": "timeseries",
   "description": "Il grafico ritorna due valori. Il valore in giallo indica in secondi il tempo total durante il quale nessun processo è stato in graod di progredire a causa della congestioni I/O. Il secondo valore quello in rosa indica il tempo totale  che i processi ahnno atteso a causa della congestione I/O",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_pressure_io_stalled_seconds_total[$__rate_interval])",
     "legendFormat": "I/O stalled time  by {{instance}}"
    },
    {
     "expr": "rate(node_pressure_io_waiting_seconds_total[$__rate_interval])",
     "legendFormat": "I/O waiting time by {{instance}}"
    }
   ]
  },
  {
   "title": "Numero di processi in runnning e in blocked ",
   "type": "timeseries",
   "description": "Il grafico restituisce due valori. Il primo, quello di colore OKOKOK, è il numero di processi in running. Il secondo valore è il numero di processi in blocked in attesa del completamento della I/O",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_procs_running",
     "legendFormat": "Numero di processi in running su {{instance}}"
    },
    {
     "expr": "node_procs_blocked",
     "legendFormat": "Numero di processi blocked su {{instance}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Il grafico ritorna 4 valorri. Il primo  valore rappresenta il numero totale di \"page faults\" verificati nel sistema negli ultimi 5 minuti. Il secondo valore ritorna il numero totale di page che sono state caricate dal disco alla RAM(paging in) negli ultimi 5 minuti. Il terzo valore ritorna il numero toale di page che sono state scritte dalla RAM al disco (paging out) negli ultimi 5 minuti ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(node_vmstat_pgfault[5m])", "legendFormat": "Page faults" },
    { "expr": "rate(node_vmstat_pgpgin[5m])", "legendFormat": "Paging in" },
    { "expr": "rate(node_vmstat_pgpgout[5m])", "legendFormat": "Paging out" }
   ]
  },
  {
   "title": "Numero di processi in runnning ora",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_procs_running", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Clock sncronizzato o meno con un reliable server",
   "type": "gauge",
   "description": "Il grafico ritorna il valore TRUE se il clock è sincronizzato con un reliable server, FALSE altrimenti",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_timex_sync_status", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "type": "stat",
   "description": "Il grafico ritorna due valori. Il primo è il tempo totale in secondi che il processo deve aspettare per avere disponibile la CPU. Il secondo invece è il tempo totale di attesa che il processo deve aspettare per avere la memoria ",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_pressure_cpu_waiting_seconds_total[$__rate_interval])",
     "legendFormat": "Tempo attesa cpu "
    },
    {
     "expr": "rate(node_pressure_memory_waiting_seconds_total[$__rate_interval])",
     "legendFormat": "Tempo attesa RAM"
    }
   ]
  },
  {
   "title": "Tempo di blocco dovuto a congestione memoria",
   "type": "bargauge",
   "description": "Il grafico ritorna il tempo totale durante il quale nessun processo è stato in grado di progredire a causa della congestione della memoria",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_pressure_memory_stalled_seconds_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sencondi spesi da un processo in attesa di una CPU e secondi per eseguire un processo",
   "type": "timeseries",
   "description": "Il grafico ritorna il numero di secondi spesi trascorsi dal processo in attesa di una particolare CPU e  indica il numero di secondi di cui la CPU ha bisogno per eseguire un processo",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_schedstat_waiting_seconds_total[$__rate_interval])",
     "legendFormat": "Seconds spent by processing waiting for the CPU: {{cpu}} by {{instance}}"
    },
    {
     "expr": "rate(node_schedstat_running_seconds_total[$__rate_interval])",
     "legendFormat": "Seconds CPU {{cpu}} spent running a process by {{instance}} "
    }
   ]
  },
  {
   "type": "stat",
   "description": "Il grafico ritorna due valori, entrambi riguardano il numero di timeslice eseguiti da una particolare cpu",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_schedstat_timeslices_total[$__rate_interval])",
     "legendFormat": "Timeslice eseguiti dalla cpu: {{cpu}} "
    }
   ]
  }
 ]
}