{
 "title": "Disk performance by remote machine",
 "tags": [ "Disk" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Numero di byte(SI) scritti",
   "type": "timeseries",
   "description": "Il grafico restituisce il numero totale di byte scritti con successo su disco",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Numero di scritture completate",
   "type": "timeseries",
   "description": "Il grafico restituisce il numero di tutte le scritture completate con sucesso",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Secondi spesi per tutte le scritture",
   "type": "timeseries",
   "description": "Il grafico restituisce il numero totale di secondi spesi per tutte le scritture (write) su disco",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(node_disk_write_time_seconds_total[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Nunmero di byte(SI) letti ",
   "type": "timeseries",
   "description": "il grafico retituisce il numero totale di byte letti con successo dal disco sda e sr0",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Numero di letture completate",
   "type": "timeseries",
   "description": "Il grafico resistuisce il numero di letture(read) completate con successo sul disco",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Secondi spesi per tutte le letture su disco",
   "type": "timeseries",
   "description": "Il grafico restituisce in numero di tutte le letture (read) fatte sul disco in secondi ",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Tempo totale per fare una discard sul disco",
   "type": "timeseries",
   "description": "Il grafico ritorna il tempo totale che il kernel ha impiegato per eseguire le operazioni di \"discard\" sul disco.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(node_disk_discard_time_seconds_total[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Numero di scarti completati con successo",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 32 },
   "targets": [
    {
     "expr": "rate(node_disk_discards_completed_total[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Numero totale di settori scartati correttamente",
   "type": "timeseries",
   "description": "Il grafico resituisce il numero totale di settori scartati con successo(sectors discarded successfully)",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 32 },
   "targets": [
    {
     "expr": "rate(node_disk_discarded_sectors_total[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Tempo totale ponderato speso nelle operazioni di I/O ",
   "type": "timeseries",
   "description": "Il grafico restituisce il tempo ponderato in secondi speso nelle opezioni di I/O. Il termine \"ponderato\" significa che il tempo speso per le operazioni di I/O è stato calcolato tenendo conto del carico di lavoro e che ci sono alcune operazioni di I/O che richiedono più tempo o che coinvolgono un maggior numero di dati hanno un impatto maggiore sul valore della metrica.\nQuesto fornisce una misura più accurata del carico di lavoro I/O rispetto al semplice conteggio del numero di operazioni di I/O.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Numero di I/O attualmente in corso",
   "type": "stat",
   "description": "Il graficoo resistuisce il numero di operazioni I/O attualmente in corso",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_disk_io_now", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Numero totale di secondi spesi da tutte le richieste di flush",
   "type": "timeseries",
   "description": "Il grafico ritorna il numero di secondi spesi da tutte le richieste di tipo flush. Un \"flush\" è un'operazione che forza la scrittura dei dati dalla cache del sistema operativo al disco fisico. Questo è importante per garantire l'integrità dei dati, specialmente in caso di interruzione di corrente o crash del sistema",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_disk_flush_requests_time_seconds_total[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Numero totale di richieste \"flush\" coompletate",
   "type": "timeseries",
   "description": "Il grafico ritorna il numero totale di richieste \"flush\" coompletate con successo ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_disk_flush_requests_total[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}