{
 "title": "Filesystem for all machines",
 "description": "Metriche riguardanti il fyilesystem",
 "tags": [ "FIlesytem" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Spazio libero del Filesystem incluso root",
   "type": "bargauge",
   "description": "Questa grafico ritorna la quantità totale di spazio libero sul filesystem (in byte (SI)).\nInclude lo spazio che è riservato a root.\nQuindi, in sostanza, riflette lo spazio fisico libero totale sul disco.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_filesystem_free_bytes ", "legendFormat": "{{device}} di {{instance}}" }
   ]
  },
  {
   "title": "Filesystem available bytes  per utenti diversi da root",
   "type": "stat",
   "description": "Il grafico ritorna la quantità di spazio libero disponibile per gli utenti non-root.\n",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes ",
     "legendFormat": "{{device}} by {{mountpoint}} di {{instance}}"
    }
   ]
  },
  {
   "title": "Numero totale di interrupt serviti in un certo periodo di tempo ",
   "type": "timeseries",
   "description": "Numero totale di interrupt serviti",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(node_intr_total [$__rate_interval])",
     "legendFormat": "Conteggio Interrupts di {{instance}}"
    }
   ]
  },
  {
   "title": "Carico medio del sistema (load average)",
   "type": "timeseries",
   "description": "Questo pannello è composto dai risultati di tre query diverse che riguardano il carico medio del sistema (load average) in diversi intervalli di tempo. In particolare, il primo riguarda il load average nell'ultimo minuto, il secondo negli ultimi 5 minuti e il terzo negli ultimi 15 minuti.",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "node_load1",
     "legendFormat": "load average nell'ultimo minuto di {{instance}}"
    },
    {
     "expr": "node_load5",
     "legendFormat": "load average negli ultimi 5 minuti di {{instance}}"
    },
    {
     "expr": "node_load15",
     "legendFormat": "load average negli ultimi 15 minuti di {{instance}}"
    }
   ]
  },
  {
   "title": "Filesystem size in Gigabyte",
   "type": "barchart",
   "description": "Il grafico restituisce la size di ogni componente del filesystem",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_filesystem_size_bytes ", "legendFormat": "{{device}} di {{instance}}" }
   ]
  },
  {
   "title": "Errore raccolta statistiche di ogni filesystem",
   "type": "gauge",
   "description": "Quando uno o più grafici è a 1 vuol dire che c'è un errore nella raccolta delle statistiche di un uno o più device, invece quando è a 0 vuol dire che non ci sono errori",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_device_error unless node_filesystem_device_error{device=~\"gvfsd-fuse|portal\"}",
     "legendFormat": "{{device}} by {{mountpoint}} di {{instance}}"
    }
   ]
  },
  {
   "title": "Numero totale di inode",
   "type": "stat",
   "description": "Misura il numero totale di \"file nodes\" (inode) sul filesystem.\nQuesta metrica è utile per monitorare il numero di file che sono creati sul filesystem e queli che possono essere creati",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_files ",
     "legendFormat": "{{device}} by {{mountpoint}} di {{instance}}"
    }
   ]
  },
  {
   "title": "Numero di inode liberi disponibili su ogni filesystem",
   "type": "stat",
   "description": "Il grafico ritorna il numero di inode liberi disponibili su un filesystem. Quindi mi dice quanti nuovi file o directory possono essere creati sul filesystem prima di esaurire gli inode",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_files_free ",
     "legendFormat": "{{device}} by {{mountpoint}} di {{instance}}"
    }
   ]
  }
 ]
}