{
 "title": "RAM of all macchines",
 "tags": [ "Memory" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Analisi dello spazio della Memoria",
   "type": "bargauge",
   "description": "IN questo grafico vengono ritornati quattro valori diversi. Il primo riguarda la prorzione di memoria availeble quindi quella che è disponibile a avviare nuove applicazioni. Il secondo valore ritorna il numero di byte della memoria liberi quindi quelli completamente inutilizzati dal sistema. Il terzo valore ritornato dalla query indica la quantità di byte  di emoria bloccata per non essere soggetta a swapping. Il quarto valore indica semplicemente la quantità totale di memoria presente sul sistema",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "av_mem {{instance}}" },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "mem_free {{instance}}" },
    { "expr": "node_memory_Mlocked_bytes ", "legendFormat": "Mem locked {{instance}}" },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": " Mem tot {{instance}}" }
   ]
  },
  {
   "title": "Analisi della Memoria di Swap",
   "type": "bargauge",
   "description": "Il grafico ritorna tre valori. Il primo restituisce la dimensione totale dello spazio di swap configurato nel sistema. Il secondo indica la quantià di spazio attualmente libero e quindi disponibile all'uso. Il terzo invece indica la quantità di memoria che è attualmente \"cached\" in RAM ",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_SwapTotal_bytes", "legendFormat": "Mem tot swap di {{instance}}" },
    { "expr": "node_memory_SwapFree_bytes", "legendFormat": "mem swap free di {{instance}}" },
    {
     "expr": "node_memory_SwapCached_bytes",
     "legendFormat": "mem swap \"cached\" di {{instance}}"
    }
   ]
  },
  {
   "title": "Quantità di memoria RAM che contiene pagine (dirty)",
   "type": "timeseries",
   "description": "Il grafico restituisce la quantità di memoria RAM che contiene pagine \"sporche\" (dirty)",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_Dirty_bytes", "legendFormat": "{{__name__}} of {{instance}}" }
   ]
  },
  {
   "title": "Numero di byte corrotti ",
   "type": "gauge",
   "description": "Il grafico ritorna il numero di byte corrotti in RAM",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_HardwareCorrupted_bytes",
     "legendFormat": "hardware corrupted {{instance}}"
    }
   ]
  },
  {
   "title": "Memoria allocata per cpu",
   "type": "gauge",
   "description": "Il grafico resitutisce la quantità di memoria allocata per la cpu",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_Percpu_bytes", "legendFormat": " {{instance}}" }
   ]
  },
  {
   "title": "RAM del sistema utilizzata per la cache ",
   "type": "gauge",
   "description": "Il grafico ritorna la quantità di memoria RAM del sistema utilizzata per la cache del file system",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_Cached_bytes",
     "legendFormat": "node mem chached of {{instance}}"
    }
   ]
  },
  {
   "title": "Quantità di byte(SI) buffer del sistema.",
   "type": "gauge",
   "description": "Il grafico ritorna la quantità di memoria in byte(SI) utilizzata dai buffer del sistema.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_Buffers_bytes",
     "legendFormat": "node mem buffer of {{instance}}"
    }
   ]
  },
  {
   "title": "Dati sulle Huge pages",
   "type": "bargauge",
   "description": "Il grafico ritorna 3 valori. Il primo valore indica il numero totale delle Huges Pages in uso. Il secondo valore ritorna il numero di Huges Pages attualmente libere e disponibili nel sistema (quando è uguale a 0 vuol dire che tutte le Huge Pages configurate sono in uso). Il terzo valore ritorna la dimensione di ogni Huge Page",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_HugePages_Total",
     "legendFormat": "Huge Pages totali di {{instance}}"
    },
    {
     "expr": "node_memory_HugePages_Free",
     "legendFormat": "Huge Pages libere di {{instance}}"
    },
    {
     "expr": "node_memory_Hugepagesize_bytes",
     "legendFormat": "Dimensioni dele Huge Pages di {{instance}}"
    }
   ]
  },
  {
   "title": "Memoria per le page table",
   "type": "gauge",
   "description": "Il grafico restituisce la quantità di Ram usata dal kernel per le page table in byte(SI)",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_PageTables_bytes",
     "legendFormat": "page_table byte of {{instance}}"
    }
   ]
  },
  {
   "title": "Quantità di RAM mappata direttamente in blocchi da 1GB e da 2MB",
   "type": "bargauge",
   "description": "Il grafico ritorna informazioni sulla quantità di memoria RAM mappata direttamente in blocchi da 1GB e in blocchi da 2MB",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_DirectMap1G_bytes", "legendFormat": "1G mem directMap of {instance}" },
    {
     "expr": "node_memory_DirectMap2M_bytes",
     "legendFormat": "2MB mem directMap of {instance}"
    }
   ]
  }
 ]
}